### PR TITLE
fixed copy & paste error in Trajectory::is_phase_synchronizable

### PR DESCRIPTION
**Pull request by stefanbesler**
I am thinking about porting your code to TwinCAT; Looking through the code I found this copy & paste error

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
off-topic but:

> I am thinking about porting your code to TwinCAT

would there be a chance you'd make that port available OSS? I'd be interested in that.

**Comment by pantor** [comment]
Hi @stefanbesler, thanks for catching this error! If there is anything you need for porting Ruckig to TwinCAT, I'll be happy to help.

**Comment by stefanbesler** [comment]
@gavanderhoorn yes, I want to do, after all @pantor open sourced this library as well, would be pretty unfair to do a closed source port :-D , I'll keep you updated.
thanks @pantor, the code seems pretty straight forward to port, I love your coding style.

**Comment by Danielxyz123** [comment]
@stefanbesler 

Does Twincat support c++17 ? Or is it neccessary to change the code to c++ 14? I would like to use ist on a B&R PLC, but there's no support for c++17. So, i think it's a lot of work to get it run...

**Comment by gavanderhoorn** [comment]
@stefanbesler wrote:
> yes, I want to do, after all @pantor open sourced this library as well, would be pretty unfair to do a closed source port :-D 

you wouldn't be the first :)

> I'll keep you updated.

would you create a repository somewhere? Then I could simply *watch* it.

**Comment by stefanbesler** [comment]
@Danielxyz123 I want to port the code to structured text ( iec 61131-3 )
@gavanderhoorn yes sure, let me get some work done before though

**Comment by gavanderhoorn** [comment]
> @gavanderhoorn yes sure, let me get some work done before though, it is quite a bit of code

empty repositories can be watched as well :)

Could also provide a venue for discussion -- perhaps even alternative approaches to full ports?

**Comment by stefanbesler** [comment]
@gavanderhoorn here we go https://github.com/stefanbesler/ruckig_TC3_port

**Comment by traversaro** [comment]
Thanks a lot @stefanbesler !  I can't promise anything and I have no idea on how is easy is to maintain iec 61131-3 libraries that target different vendors, but once the TC3 port is there, I would be interested in looking if we can get it to work on CODESYS. fyi @singhbal-baljinder

**Comment by pantor** [comment]
@Danielxyz123 Regarding compiling Ruckig with C++14, somebody already asked in #28 about the required changes for C++11. If downgrading to C++14 would be really helpful for you, feel free to reach out once again, as it should be quite easy for me to get it running.

**Comment by pantor** [comment]
@Danielxyz123 There is now a [script](https://github.com/pantor/ruckig/blob/master/patch-c%2B%2B11.sh) to patch Ruckig for C++11.

**Comment by Danielxyz123** [comment]
Wow thats great! Thanks a lot 👍.

**Pull request merged**
