### PR TITLE
Add support for installation of the C++ library

### PR DESCRIPTION
**Pull request by traversaro**
First of all, thanks for the amazing library @pantor , I can't wait for the paper to be out. 

This PR just adds some modifications to ensure that the library can be consumed in CMake using `find_package`, to check that it is working I also added an example CMakeLists.txt in the example directory.

Simple commands to test it on Linux:
~~~sh
git clone https://github.com/traversaro/ruckig -b add-install-support
cd ruckig
mkdir build
cmake -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_BUILD_TYPE=Release ..
make install
export CMAKE_PREFIX_PATH=`pwd`/install
cd ../examples
mkdir build
cd build
ccmake ..
make
./ruckig-example-position
~~~

### CODE REVIEW

**Comment by traversaro** [comment]
cc @ahoarau

**Comment by traversaro** [comment]
By the way, I noticed that the version in [CMake](https://github.com/pantor/ruckig/blob/e029558fa415c21ad0c07bc37a70404b5ab4b480/CMakeLists.txt#L4) and [doxygen](https://github.com/pantor/ruckig/blob/e45b2c860188912a6a563c25c383966c26df6cbc/doc/Doxyfile#L41) seems to be 1.0.0 while the GitHub releases are set to 0.2.0, not sure if it is intentional or not. However, as this PR is now installing the version in the CMake config, we may want to align that.

**Comment by ahoarau** [comment]
I've played with the cmake on windows. Removed the STATIC or SHARED explicit to let the user choose. 
Also the flags are for GCC only

**Comment by traversaro** [comment]
> 
> 
> I've played with the cmake on windows. Removed the STATIC or SHARED explicit to let the user choose.
> Also the flags are for GCC only

Thanks! My plan was to fix those in subsequent PR once I received the feedback for this one.

**Comment by pantor** [comment]
Hi @traversaro, that's great to hear that you find Ruckig useful!

Thanks for your PR, the installation process was indeed not the highest priority so far... I've updated the CMake and Doxygen version to 0.2.0, so that should be fixed. Is it possible to move the `ruckig-config.cmake.in` file into the `cmake/` directory? I think then this should be good to merge.

Looking forward to further PRs!

**Comment by traversaro** [comment]
Done, thanks @pantor  for the quick feedback.

**Pull request merged**
