### PR TITLE
Adding 15_visualizer for motion planning in the browser

### PR DESCRIPTION
**Pull request by qknight**
First: Ruckig is an **awesome project**. Want to look into the math side of it soon!

This PR integrates a motion planning visualization using plotly.js and this can be used from the webbrowser.

Main goal is to learn about the nature of the parameters for educational purposes

Oh, and here is a preview:

https://lastlog.de/blog/ruckig_motion_planning.html

# open questions

This code is completely finished but it would be interesting to access the values of the individual segments, this seems to be possible according to:
* https://github.com/pantor/ruckig/issues/117
* https://github.com/pantor/ruckig/issues/144

But I can't access the values yet, do you have a hint for me?

### CODE REVIEW

**Comment by pantor** [comment]
Hi, thanks for your kind words and your pull request! 

Regarding your question, you can access the internal profiles of a calculated trajectory via `get_profiles()` and their relevant array members.

I really like the idea of a web tool to play around and get an intuition of Ruckig! Can you move your files from the examples directory to `doc/web-visualization`? Ruckig already has a copy of `nlohmann/json` in the `third_party/json` directory, so please reuse that one.

I think our goal should be to host this to make it truly accessible. I’ll take a look into that in the coming week.

**Comment by qknight** [comment]
@pantor fixed all the open points, ready to merge ;-)

**Comment by qknight** [comment]
*meeeeep*

**Comment by pantor** [comment]
Closed in favor of #164.

**Pull request closed without merging**
